### ISSUE TITLE
Saltbot causes chrome tab to crash after indeterminate amount of time

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#113] opened 2016-12-14 21:52 UTC
Saltbot crashes the saltybet.com chrome tab after indeterminate amount of time when video is enabled and not when it is off.

this occurs both on chrome and chromium, and occurs regardless of the browser window being minimized/maximized, screen on/off.

console shows no errors, it just crashes the tab and a reset is needed(close all windows, start browser again, open extension options and turn scientist back on)

For the sake of automation/hands off betting, it's crucial that the bot stays active when the machine is left, or at the very least crash logging should be setup to warn the user the extension/tab has crashed(maybe via email?) and perhaps restart itself(close chrome/chromium and restart with the intended start page being saltybet.com)

**Comment by calexil** [comment] 2016-12-14 21:58
tonight I will do some testing to try and determine why the tab is crashing.

**Comment by reconman** [comment] 2016-12-14 22:34
The extension remembers the last betting mode. For the first bet on reloads it says Monk because the data may be incomplete.

Starting with the second match it will use the previous betting mode (in most cases Scientist)

**Comment by calexil** [comment] 2016-12-14 22:36
@reconman ah, nifty

**Comment by calexil** [comment] 2016-12-20 04:15
Issue is ongoing, heres terminal output following the saltybet.com tab crashing:

https://u.teknik.io/xGUAD.Unsaved%20Document%201

**Comment by reconman** [comment] 2016-12-20 13:49
> WTF::Partitions::handleOutOfMemory()

Looks like an out of memory error to me. What is WTF::Partitions?

**Comment by calexil** [comment] 2016-12-20 19:59
well the betting rig only has 4gb of memory, but it has nothing else running....hmmm

**Comment by wujo635** [comment] 2016-12-25 04:36
It seems when toggle video is set true the Chrome tab will just keep eating up memory until it crashes.

**Comment by reconman** [comment] 2016-12-25 23:38
@wujo635 Thanks, I think I just found out how to avoid the memory leak caused by the disabled video.

@synkarius Can you please upload the new version of Saltbot so we can test if this fixed all memory leaks?

**Comment by synkarius** [comment] 2016-12-25 23:56
@reconman Done. :)

**Comment by calexil** [comment] 2016-12-27 04:09
ill pull and build today, bout to leave for vacation so we'll see if it keeps running for a week straight!

**Comment by calexil** [comment] 2017-01-06 23:02
still a little crashy, but not as bad as before.

seems to run for about a week without issues. 

Ill close this once it runs for two weeks straight with no issue

**Comment by calexil** [comment] 2017-01-10 03:17
hmm, still crashing... dangit. 

I cant for the life of me figure out why

**Comment by calexil** [comment] 2017-01-16 07:30
Okay I fired it up with gdb to get a better verbose output during the crash and got lucky

here is the output:

http://dpaste.com/1ZS83R7

I added another 4gb stick to the bot system to no avail, even memtested the memory... no issues.

for some reason, after some amount of time the main saltybet.com tab crashes *the chat tab stays alive just fine*

maybe the bot should have a self regulating feature to enforce keeping itself running.

This can be accomplished a number of ways, but the simplest would be to check 
![logout](https://cloud.githubusercontent.com/assets/3487071/21974273/c6412422-db93-11e6-9a81-9ff37fea6493.png)
the saltybet.com tab for the "logout" button/element... as long as it can be found the tab is working fine, when it is not available... a chrome restart with the last open tabs should be enforced.

this would assure hands-off betting automation.

**Comment by reconman** [comment] 2017-01-16 12:14
I think the only thing I can really do is add a config option for a keep alive mode where it opens another saltybet tab if the existing one crashed. This needs to be an option because closing the tab would result in it reopening immediately.

There is nothing I can do about the saltybet tab slowly increasing its used memory since the native saltybet scripts are the main source of memory allocation.

**Comment by calexil** [comment] 2017-01-16 22:12
hmm, well if you can figure out a way to create a keep alive feature that would be key.

I know I would greatly appreciate it, so let me know if there's anything I can do to help

**Comment by calexil** [comment] 2017-03-20 09:50
any news on a crash recovery feature?

**Comment by reconman** [comment] 2017-03-20 22:04
Those 2 months really went by fast for me. Today I have begun adding an option to the config and to the settings object. I still need to test the changes I've made.

I can't really reproduce the tab crashes on my system because I can't leave the saltbot running all week long so the crash logic just makes assumptions right now on how the tabs would behave. I don't know if chrome lists them if I query for tabs with the url "saltybet.com" or if they just produce errors if you try to send messages to them.

Either way my current uncommitted and untested code should be able to handle both cases.

**Comment by calexil** [comment] 2017-03-20 22:05
Awesome, Ill be on the lookout for the commit

**Comment by calexil** [comment] 2017-03-20 22:11
Also, I'm not sure how much it matters, but I am running ublock origin on the betting machine.

**Comment by calexil** [comment] 2017-03-22 23:24
I have error logs somewhere I know it.... I'm gonna find out where the crash is starting

**Comment by reconman** [comment] 2017-03-23 23:18
I've commited my changes for keep alive built into the background site of the extension. Whenever a chat message is read and keep alive is true then a saltybet tab will be opened if there is none or if no tab can receive the chat messages.

@synkarius Could you please update the extension in the chrome store? I've tested setting all the options on the config page and let the saltbot run for a few rounds so there should be no obvious bugs introduced by the commit.

**Comment by calexil** [comment] 2017-03-24 20:15
this feature does not seem to actually work, I tested it and the crashed chrom tabe remained and the extension did not refire a new tab

**Comment by reconman** [comment] 2017-03-24 21:15
It did not work because of Chrome's asynchronous functions where the variable values change during function call.

My newest commit should fix that. I've tested it by crashing the tab on purpose with this little script:
```
txt = "a";
while(1){
    txt = txt += "a";    //add as much as the browser can handle
}
```

**Comment by calexil** [comment] 2017-03-24 21:20
Okay I'll fire it up tonight when I get home from work

**Comment by calexil** [comment] 2017-03-25 05:11
I can now confirm this issue is resolved, the crashed tab was properly closed and a new one opened, the bot then continues to bet after a single round monk break.

excellent work @reconman !

**Comment by reconman** [comment] 2017-03-25 11:02
@synkarius Can you please upload the new version to the Chrome store?

**Comment by calexil** [comment] 2017-03-25 11:04
can we merge my restructure first? @reconman

**Comment by calexil** [comment] 2017-03-25 11:05
also I cleaned up the readme

**Comment by calexil** [comment] 2017-03-29 16:48
The auto restore function is not...functioning, Ill have more info tonight

**Comment by calexil** [comment] 2017-03-30 18:31
@reconman @ACIIL can we try to get the keep alive parts of that commit merged?

**Comment by ACIIL** [comment] 2017-03-30 20:42
eh? I am not smart to this kind of web browser coding.    Github is confusing,  It mistakened my sync update from synkarius/master as something.

If this promote was automated i am sorry.

**Comment by reconman** [comment] 2017-03-30 20:47
@calexil The keep alive will be kept, I just have to manually edit the files until all conflicts are solved.

@ACIIL One of my commits in your merge request in your own fork references this issue. Don't worry, you did nothing wrong.

**Comment by reconman** [comment] 2017-05-05 23:32
> The auto restore function is not...functioning, Ill have more info tonight

@calexil What's the status right now.

**Comment by calexil** [comment] 2017-06-07 20:45
@reconman auto restore seems to function, but the chat window now dies and does not refire correctly. this causes huge losses as the records are not being stored correctly and the bot cannot properly ascertain odds

**Closed** 2017-06-07 21:03 UTC
