### ISSUE TITLE
UI Button Disappearing

### ISSUE THREAD

**Issue by falconergithub** [synkarius/saltbot#62] opened 2015-08-17 07:24 UTC
I know this was mentioned about a month ago, but the UI button disappears for me once I actually start running the bot. It still works and it will still bet, but I can't get it to come back no matter what, so if I want to turn it off I have to disable the extension/reenable it to turn it back on.

That also means I can't adjust my settings, and I'm stuck in Scientist now and want to go back to Monk.  If I uninstall/reinstall it fixes it, but after running it a few times it will inevitably disappear again, and having to keep uninstall/reinstalling is a pain.

**Comment by synkarius** [comment] 2015-08-17 09:51
Can you provides more details? For example, exactly when does the button disappear? (After clicking it or one of the other buttons?) Which version of chrome (normal, Canary, Dragon), what operating system? Any the other chrome extensions running? Anything else relevant you can think of? 

I ask all these questions because I've never seen this and this is the first time I've heard of it, so to fix it, I'll first need to reproduce it.

**Comment by falconergithub** [comment] 2015-08-17 12:22
I'm using standard chrome 44.0.2403.155 m (which should be the most-recently updated version.)

I'm using 64 bit Windows 7 Home Premium. The only other Chrome extensions I run are Reddit Enhancement Suite and Adblock, but I have adblock disabled for twitch and saltybet domains and I am pretty sure RES only interacts with chrome when on a reddit domain.

I haven't had a chance to see exactly the "point" that the actually button disappears, but the past two times I've tried it have gone something like this:

Install -> Login to saltybet.com with UI button active -> import your char data->get initial genomes for 50 cycles -> reload -> Select bet mode, etc. At that point, it works fine and appears to be functioning normally.

It's at some point after that initial setup once I close chrome entirely and revisit saltybet.com, the button to bring up the UI simply disappears. I know it's still working - in fact, I can log on my account right now and it's betting in what I guess is scientist mode. Visiting saltybet.com still opens the twitch chrome tab as well. It's functioning entirely as if I just set it up once and never touched it again, but the pyramid to access the UI does not reappear, and it won't unless I reinstall. 

I can give you some more info if you ask for something more specific, I'm probably not savvy enough to give you any detailed code errors or anything, but I can copy from the console or something.

**Comment by synkarius** [comment] 2015-08-19 01:14
Your settings are nearly identical to mine, except that you are running a few other chrome extensions. I know they shouldn't affect the saltybet.com domain, but the only thing I can tell you to try right now is disabling them both entirely and seeing if it still happens. 

A few other times, users have reported similar problems to me, and it turned out other extensions did in fact interfere. 

Every time I give this advice, I don't expect it to work, because it shouldn't, and I don't expect it to work in your case either, but let's just rule it out.

**Comment by falconergithub** [comment] 2015-08-19 01:32
Yeah, even after disabling both, it's behaving the same. The bot runs on saltybet, but the UI is still inaccessible. Is there an alternative way to pull it up without access to the UI button?

**Comment by synkarius** [comment] 2015-08-19 01:58
Does the Google Chrome extensions page say it has any errors?

**Comment by falconergithub** [comment] 2015-08-19 02:01
Nope, no errors displayed at all

**Comment by synkarius** [comment] 2015-08-20 00:21
So I googled this a bunch, and no luck. I can take a few more guesses, but I really have no idea what's going on. 

* Are you using a proxy?
* Is it possible that you dragged the edge of the URL bar to cover the icon? (I know it's a long shot and doesn't really match your description but...)
* Computer maintenance software like CCleaner messing with it because it considers it to be junk?

I wish I could be of more help, but you're the only person I've heard report this, and I don't know how to reproduce it.

**Comment by falconergithub** [comment] 2015-08-20 22:44
I appreciate all of the help - and I know it seems like a very strange problem.

Strangely enough, I DID use a proxy once or twice when I was testing some networking stuff.

**Comment by falconergithub** [comment] 2015-08-22 11:08
Mysteriously, it came back. It seems to be working again. I never uninstalled or anything. Sorry for causing you so much trouble! I'll let you know if it gets wonky again.

**Comment by synkarius** [comment] 2015-08-22 13:57
I pushed version 2.0.3 to the Chrome store yesterday. I actually don't know why that fixed it. The update was targeted at some other stuff.

**Comment by reconman** [comment] 2015-08-22 19:32
It fixed it because the extension was reinstalled during the update. He stated that uninstalling and installing the extension again fixes the problem.

**Comment by falconergithub** [comment] 2015-08-23 06:34
Ah yea, it disappeared again. The 2.0.3 counted as a reinstall as reconman stated, but the UI button is gone again, but still functioning as usual. I'm going to attempt to see if I can see what causes it to trigger.

**Comment by falconergithub** [comment] 2015-08-23 06:50
So yeah, after some extensive testing, closing the browser AT ALL makes the UI button disappear and not come back. I've tested it about 5 times now, and it happens regardless of whether or not I touch the button at all. My settings haven't changed at all, I haven't even touched a proxy or anything this time. It's simply install->button shows up->close chrome->gone.

If I set it up beforehand, the bot will function with the settings I have selected for it (which it is doing now.)

I'll reopen just in case someone else happens to get the same issue so this thread is more visible. I appreciate you trying to fix it. In the meantime I might try to tinker with specific chrome settings to see what the hell its problem is. Unfortunately I just lost a bunch of collected character data when I reinstalled so I'll let you know if I figure it out.

**Comment by synkarius** [comment] 2015-08-23 16:00
This seems to be exactly what you're experiencing. Let me know if anything in here helps:
https://productforums.google.com/forum/#!topic/chrome/7oImEYDuQyE

**Comment by iChai** [comment] 2016-01-18 21:11
Yeah, I notice this happened to me on my Linux machine today. I wasn't able to import my records because the UI kept closing on me so I had to do a trick to get the UI window to stay open so that I could update the records and after I did that, I went to log in and the Chrome UI button disappeared. I ended up having to re-install the extension to get the icon back.

**Closed** 2016-03-23 22:43 UTC
