### ISSUE TITLE
Unlimted tabs

### ISSUE THREAD

**Issue by 7474747** [synkarius/saltbot#76] opened 2016-01-18 09:38 UTC
I tried to use the bot and go afk, but my computer lagged out because it kept opening more and more tabs of twitch chat. I don't know how to get it to stop.

**Comment by Zyrixion** [comment] 2016-01-18 11:43
Are you using the chrome store version of the script, and did this happen to you from the get-go after installing it, or is it an issue that just occurred?  Have you tried closing and re-opening chrome and doing it again?  Same question goes for refreshing the saltybet tab and reinstalling the extension entirely.

**Comment by Blix3r** [comment] 2016-01-19 00:19
I'm having the same problem, it continues opening up chat in a new window and never stops. Tried reinstalling and restarting chrome, nothing has helped.

**Comment by synkarius** [comment] 2016-01-19 00:42
Thus far, I am unable to reproduce this issue. If I can't get it to happen in the next day, I will temporarily roll back the recent update.

**Comment by Blix3r** [comment] 2016-01-19 00:54
I seemingly fixed it by restarting my computer after installing the bot. Don't worry synkarius it seems to be working properly now however I'm not sure about 7474747

**Comment by synkarius** [comment] 2016-01-19 01:05
Even if @7474747's problem is resolved using your method, there are around 500 people using the bot, some portion of whom will be affected by this. The bug has to be fixed without workarounds.

**Comment by Blix3r** [comment] 2016-01-19 01:43
@synkarius I am having this error pop up fairly frequently. Any idea what it might be? mp.twitch.tv/crossdomain.xml:1 GET http://mp.twitch.tv/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT

**Comment by reconman** [comment] 2016-01-19 08:26
@synkarius There's no explanation as to why it would happen right now. The relevant part is in twitch_background.js and was simply changed from twitch.tv/saltybet to twitch.tv/saltybet/chat.

@Blix3r That's just a general message from twitch which is probably caused by your adblocker.

**Comment by synkarius** [comment] 2016-01-19 10:51
@reconman Hmm. If you think it's unrelated to the update, then I won't roll back. No point if it'd happen without it too.

@Blix3r, @7474747 I still can't reproduce it. Can you give me any more information which might be relevant? Other plugins running? Special version of Chrome? (Like Chromium, Canary, or Komodo?) Using a proxy, or Tor, or Amazon AWS? Anything even slightly relevant helps.

**Comment by 7474747** [comment] 2016-01-19 23:21
No other plugins running, and I'm using regular Google Chrome as far as I know. It never used to open tabs nonstop until recently, so idk what's up :/

**Comment by reconman** [comment] 2016-01-20 00:23
@synkarius @7474747 I've added some detailed logging to twitch_background.js so the script will write to the console which url was opened and which urls are open right now. Please update the extension in the store.

@7474747 Were you able to reproduce it? If so please make sure that the latest version is installed (2.1.1) and open the chrome://extensions page and then click on background site for Saltbot. After that a window with HTML code in it should appear where you have to press F12. Please copy the last 2 messages and paste it into a comment here.

The log should look like this:
> twitch_background.js:37
> The new tab has the url 'http://www.twitch.tv/saltybet/chat'

> twitch_background.js:41
> ["https://www.youtube.com/watch?…", "https://www.facebook.com/", "http://mangafox.me", "https://github.com/synkarius/saltbot/issues/76", "http://www.saltybet.com/", "chrome://extensions/",  "http://www.twitch.tv/saltybet/chat"]

You can remove things you don't want to share from the list of urls. In case the list of urls is not there but Array[?] with any number instead of the ? click on the arrow left of Array to show the urls.

**Comment by synkarius** [comment] 2016-01-20 01:15
Updated. Should be up within an hour.

**Comment by synkarius** [comment] 2016-01-21 00:10
@7474747, @Blix3r, if either of you are still getting this, what does @reconman's updated logging show?

**Comment by Blix3r** [comment] 2016-01-21 08:25
@synkarius I can not reproduce the bug after my initial fix. 

Logging: 
The new tab has the url 'http://www.twitch.tv/saltybet/chat'
twitch_background.js:41 ["https://www.youtube.com/watch?v=fspx_gCmAjs&list=PList4oP5ulLXrB6_QNCe33dOQ4E0HEzIl&index=4#t=48.098", "https://github.com/synkarius/saltbot/issues/76", "chrome://extensions/", "http://www.saltybet.com/", "http://www.twitch.tv/saltybet/chat"]

**Comment by 7474747** [comment] 2016-01-21 20:55
![screenshot_2](https://cloud.githubusercontent.com/assets/16756204/12494214/8bcfeadc-c04e-11e5-8e8e-ffdbaf8649ac.png)

twitch_background.js:37 The new tab has the url 'http://www.twitch.tv/saltybet/chat'
twitch_background.js:41 ["chrome://extensions/?id=cjpalhdlnbpafiamejdnhcphjbkeiagm", "http://www.saltybet.com/", "https://www.twitch.tv/saltybet/chat", "http://www.twitch.tv/saltybet/chat"]

**Closed** 2016-01-21 21:21 UTC

**Comment by reconman** [comment] 2016-01-21 21:53
The issue was that somehow your twitch chat was https:// and not http://. Every time the twitch chat opened, it would reload the site as https. Since the script didn't search for https but for http, it would open a new tab after every match.

Thank you for reporting the bug, I fixed all scripts so they work with http and https, even though saltybet can't display the chat and video when loaded with https.

**Comment by synkarius** [comment] 2016-01-21 22:21
Uploaded. Thanks @reconman.

**Comment by reconman** [comment] 2016-01-21 22:36
@synkarius Forgot to push a commit, sorry. Adds the logging of the urls back in.

**Comment by synkarius** [comment] 2016-01-22 00:01
It's all good. Uploaded.
