### ISSUE TITLE
Maximum Bet not working

### ISSUE THREAD

**Issue by MoonBootsForHire** [synkarius/saltbot#228] opened 2019-05-22 01:55 UTC
Maximum bet limiter isn't working when bot is set to all modes, the box becomes unchecked and the value defaults back to 10,000 after clicking off the bot's UI. Disabled all AdBlockers/script blockers, and it still won't cap a maximum bet. The crazy thing keeps betting 60k-100k when I only want to use 20k max every bet.

It's not an ad blocker, script blocker or other extension, SaltBot is the only extension running on Chrome.

**Comment by MoonBootsForHire** [comment] 2019-05-22 02:08
I tried to leave the UI open with the settings selected to see if the maximum bet feature works at all and it still completely ignored them, even though the box was ticked and "active". For some odd reason this feature no longer seems to work, I've only been using the SaltBot for a day though.

![image](https://user-images.githubusercontent.com/26130937/58142426-e1d28e80-7c3e-11e9-8638-bf9051c3808f.png)

**Comment by calexil** [comment] 2019-05-22 23:54
dupe of #223

**Closed by calexil** 2019-05-22 23:54 UTC
Labels: Duplicate
