### ISSUE TITLE
SaltBot gets stuck when trying to Update genetic weights.

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#216] opened 2018-05-21 22:00 UTC
https://www.reddit.com/r/saltbot/comments/8kpdiw/saltbot_gets_stuck_when_trying_to_update_genetic/

I can confirm the same issue, the extension completely freezes, and nothing happens in inspector. 

no new generations

**Comment by SethRose** [comment] 2018-05-23 04:47
Hi,Original poster of the Reddit Thread.
Just wanted to add that i tried both the Chrome app and built the app myself to see if there was a difference,so far it still remains broken.

**Comment by calexil** [comment] 2018-05-23 17:51
thanks @SethRose we'll look into it

**Comment by reconman** [comment] 2018-05-27 18:26
Error was caused by an index out of bounds exception that came from my changes on how chromosomes are calculated for the next generation. When you import a chromosome, the chromosome pool has size 1, so it can't iterate over the best 10 chromosomes to mate them.

Should be fixed with commit 79934adab3ba01eb9da517

**Closed** 2018-05-27 18:26 UTC
Labels: Bug
